name: war CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - name: checkout code
         uses: actions/checkout@v3

     steps:
      - name: Set up JDK 11
        uses: actions/checkout@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
 
     steps:
      - name: war
        run: mvn clean package
